### ISSUE TITLE
Qbittorrent 5.0.0 in Error 

### ISSUE THREAD

**Issue by MARIUSVAMPIRE** [fedarovich/qbittorrent-net-client#30]
Result Error after Call GetTorrentListAsync

Error 1
JsonSerializationException: Error converting value "stoppedDL" to type 'QBittorrent.Client.TorrentState'. Path '[0].state', line 1, position 6763.

Error 2
ArgumentException: Requested value 'stoppedDL' was not found.

**Comment by fedarovich** [comment]
I'm working on fixing compatibility with QBittorrent 5.0.

Unfortunately, they introduced several breaking changes to the API, so it might take me a few days to fix all issues and create a new release.

**Comment by fedarovich** [comment]
Fixed in 1.9.24285.1
