### ISSUE TITLE
[Suggestion] Add magnet support 

### ISSUE THREAD

**Issue by HadiSDev** [fedarovich/qbittorrent-net-client#6]
Hey.

Is it possible to get magnet url support?

**Comment by fedarovich** [comment]
Hello.

You can add a torrent by a magnet link in the current version. For example:
```
var request = new AddTorrentUrlsRequest(new Uri("magnet: ..."));
await client.AddTorrentsAsync(request);
```

Or did you mean something else?

**Comment by HadiSDev** [comment]
@fedarovich Oh thank. I actually tried this but did not realize it actually added the torrent. Thank you :)
