### ISSUE TITLE
Pausing/Stopping/Deleting?

### ISSUE THREAD

**Issue by Krutonium** [fedarovich/qbittorrent-net-client#8]
I've been playing with the API and I can't find any functions for actually stopping or removing torrents from the client. Am I missing something or is this not implemented?

**Comment by fedarovich** [comment]
Here you are:
[Delete/Remove](https://fedarovich.github.io/qbittorrent-net-client-docs/api/QBittorrent.Client.QBittorrentClient.html#QBittorrent_Client_QBittorrentClient_DeleteAsync_System_Boolean_System_Threading_CancellationToken_)
[Pause](https://fedarovich.github.io/qbittorrent-net-client-docs/api/QBittorrent.Client.QBittorrentClient.html#QBittorrent_Client_QBittorrentClient_PauseAsync_System_Threading_CancellationToken_)
